### ISSUE TITLE
Front End Refactor Epic

### ISSUE THREAD

**Issue by jarednova** [Upstatement/blades#55]
# Goals of this project
- Reduce the load time of each view of the site, make “speed” a major feature to surprise and delight
- Keep everything visually the same. Lord knows lots of designers want to get in there and tweak things. They should too! Just not as a part of this project. The following things should not get in the way of this: visual changes, CSS reorganization (unless css org becomes a blocker).
- Maintain a platform for the future the way upstatement.com is going to continue is through asynchronous design and development where (for example) Tito might redesign the about or home page and can do so in a way that he can do this type of activity solo while still maintaining the “speed as a feature” feature.

### Technical info
While I assume Ember and WP-API are the tools necessary to complete these goals, they are not requirements. Rather, these are:
- Keep editing of site visuals easy for staff. Tito, Nathan, Mike should continue to be able to tweak layout, CSS, etc. without much resistance
- No major rebuilding of Case Studies A significant amount of effort has gone into making the case studies for HLR, Hechinger, etc. It’s not a big deal to move the small amount of content for these outside of WordPress, but we must avoid refactoring of the code that powers these

# Acceptance Criteria

### Performance
- [ ] The homepage first load beats or is consistent the current Pingdom metrics of 67/100, 54 requests, 1.41s load time and 910.2 page size. 
- [ ] Page to page load time is reduced. On top three paths
  - [ ] Home to About
  - [ ] Timber to Home
  - [ ] Hechinger to Portfolio
- [ ] Loading transitions help guide users

### Case Studies
- [ ] The HLR case study is visible at the same URL and is visually indistinguishable from its current form
- [ ] The Hechinger case study is visible at the same URL and is visually indistinguishable from its current form
- [ ] The Global News case study is visible at the same URL and is visually indistinguishable from its current form
- [ ] The Kellogg case study is visible at the same URL and is visually indistinguishable from its current form
- [ ] The Boston.com case study is visible at the same URL and is visually indistinguishable from its current form
- [ ] The case study archive page is visible at the same URL and is visually indistinguishable from its current form
- [ ] An editing process is document for how to create case studies in this new framework

### Blog
- [ ] Content lives at the same URLs (or automatically redirects) and is visually close to its current form
- [ ] New posts can be created with the same workflow as now. If there’s a difference, this difference is documented in the blades repo wiki

### Jobs
- [ ] Content lives at the same URLs and is visually close to its current form
- [ ] New posts can be created with the same workflow as now. If there’s a difference, this difference is documented in the blades repo wiki

### About
- [ ] Content lives at the same URLs and is visually close to its current form
- [ ] New people blocks can be created with the same workflow as now. If there’s a difference, this difference is documented in the blades repo wiki

### Homepage
- [ ] Content lives at the same URLs and is visually close to its current form

### Browser
- [ ] The site meets standard “targeted” language for Google Chrome on desktop
- [ ] The site meets standard “targeted’ language for iOS 8 on an iPhone 6 with necessary exceptions for performance
- [ ] The site meets standard “supported” language for IE 11 on Windows 7
- [ ] The site meets standard “supported” language for newest Chrome on Android Krispy Kreme
- [ ] The site meets standard “supported” language for newest Firefox on Mac OSX
- [ ] The site meets standard “legacy support” for IE 9 on Windows 7
